### ISSUE TITLE
Verbesserung: E-Mail Feld

### ISSUE THREAD

**Issue by miladfakiry** [smat91/ContactManager#2]
E-Mail Feld braucht mindestens ein "@" und ein "."
Momentan kann man m.fakiry3@gmailcom eingeben und es wird als E-Mail erkannt.
![E-Mail_verbessern](https://user-images.githubusercontent.com/78559990/132984545-388c560f-c808-4a0e-a1fe-5f64fc2017ad.JPG)

**Comment by smat91** [comment]
Erledigt
