### ISSUE TITLE
Verbesserung: Spalten verkleinern

### ISSUE THREAD

**Issue by miladfakiry** [smat91/ContactManager#3]
Ist es möglich von Beginn an die Spalten zu verkleinern? ID bräuchte noch lange nicht so viel Platz, oder auch bei den Notizen (aber da verstehe ich es, da der Platz nicht komplett gebraucht wird.
![Felder verkleiner_ID_etc](https://user-images.githubusercontent.com/78559990/132984582-69580f8d-ac2f-4ded-b50a-a3ad014be9c9.JPG)

**Comment by smat91** [comment]
Erledigt
