### ISSUE TITLE
Verbesserung: Pflichtfelder bevor man Speichern kann?

### ISSUE THREAD

**Issue by miladfakiry** [smat91/ContactManager#4]
Gibt es Felder, welche unbedingt notwendig sind, bevor der Kunde, Mitarbeitende oder Lernende gespeichert werden kann?
![gibt es pflichtfelder bevor man speichern möchte](https://user-images.githubusercontent.com/78559990/132984602-d395c1d0-6e3d-4d31-b889-3a5f0bbd9b98.JPG)

**Comment by smat91** [comment]
Mindestens Vor- und Nachname muss eingegeben werden bevor der Datensatz gespeichert werden kann

**Comment by miladfakiry** [comment]
Reicht das so für uns? Wenn ja, dann alles gut.. Aber mindestens, Adresse Telefon und Email wäre meiner Meinung nach wichtig, so können wir auch in realen Use Cases "unnötige" Erstellungen von Kunden, MA etc

**Comment by smat91** [comment]
Stimmt. Ich habe es noch erweitert.
