### ISSUE TITLE
Verbesserung: Exception Handling Mitarbeitende / Lernende

### ISSUE THREAD

**Issue by miladfakiry** [smat91/ContactManager#5]
Beim Erstellen von MA oder AZUBI kommt es noch zu einem Fehler, wenn man beim letzten Feld (glaube ich) nichts einträgt.
Bitte kurz testen
![in_diesem Bereich ist noch ein Fehler_ klick mal herum](https://user-images.githubusercontent.com/78559990/132984632-4a45135f-ae76-42b8-969b-a523fbf80527.JPG)

**Comment by smat91** [comment]
Erledigt
