### ISSUE TITLE
Verbesserung: Feld Ort kann Leerzeichen oder Sonderzeichen beinhalten

### ISSUE THREAD

**Issue by miladfakiry** [smat91/ContactManager#6]
Es gibt Orte in der Schweiz oder auch im Ausland, welche aus 2 Wörtern bestehen, oder Sonderzeichen haben.
![Ort_Leerzeichen_Sonderzeichen](https://user-images.githubusercontent.com/78559990/132984672-d71e69a7-7242-4665-a10a-f115cd50aa58.JPG)

**Comment by smat91** [comment]
Erledigt
