### ISSUE TITLE
Verbesserung: Priorisierung bei aktiv und inaktiv

### ISSUE THREAD

**Issue by miladfakiry** [smat91/ContactManager#7]
Wäre das eine gute Idee, wenn wir die inaktiven Kunden immer zu unterst von der Liste anzeigen könnten?
![prio aktiv inaktiv](https://user-images.githubusercontent.com/78559990/132984715-b8f1e89a-342c-480f-9005-c6936b2a1a19.JPG)

**Comment by smat91** [comment]
Aktuell wird nach Id sortiert will man nach Status sortieren kann man einfach über einen Klick auf Status die Sortierung anpassen.
