### ISSUE TITLE
Verbesserung: Willkürliches Drücken bei Feldern

### ISSUE THREAD

**Issue by miladfakiry** [smat91/ContactManager#8]
Momentan kommen noch Fehlermeldungen, wenn man einfach nur auf Felder drückt und nichts eingibt und wieder auf einem anderen Feld drückt..
![Wo genau ist der Fehler](https://user-images.githubusercontent.com/78559990/132984744-d13e9740-c4a1-4ecd-8b76-639a0e4b3d35.JPG)

**Comment by smat91** [comment]
Erledigt
